Translatable comps
supertokens/supertokens-auth-react pull request #375
Opened 2022-01-29 09:46 UTC by porcellus

## Summary of change

Enables providing translations for all copies.

## Related issues

-   #233 

## Test Plan

- Visual testing would be great for this.
- Some tests check copies as well.

## Documentation changes

TODO:

## Checklist for important updates

-   [x] Changelog has been updated
-   [x] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `lib/ts/version.ts`
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [x] Had run `npm run build-pretty`
-   [x] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [x] If added a new recipe interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [x] If I added a new recipe, I also added the recipe entry point into the `size-limit` section of `package.json` with the size limit set to the current size rounded up.

## Remaining TODOs for this PR

-   [ ] Change base branch (or remove tppwless related parts) 
  - I used tppwless as a base branch because I wanted to extract all translations in one go.
-   [ ] Resolve TODOs in code

2022-02-01 10:48 UTC, rishabhpoddar commented
# Feedback
- [ ] Destination should be 0.18 and not thirdpartyemailpassword
- [ ] The size check if failing - need to change the limits

2022-02-01 11:36 UTC, rishabhpoddar requested changes

2022-02-01 11:36 UTC, rishabhpoddar commented on lib/ts/recipe/emailpassword/translations.ts
> +import { defaultTranslationsCommon } from "../../components/translations";
Maybe consider moving all the translations into the theme folder of each recipe.

2022-02-01 11:36 UTC, rishabhpoddar commented on examples/for-tests/src/App.js
> +        translations: {
We should consider changing the name to `translationsForLanguages`

2022-02-01 11:36 UTC, rishabhpoddar commented on examples/for-tests/src/App.js
> +        translations: {
We should move `translations` to supertokens.init and not to have a recipe level, and club all the translation related config into one object as opposed to keeping them all in the root level. You can call this `translationsForLanguages` or `languageTranslation`. The fields in the object are:
- `translations` (contains the variable key values for different diff langs
- `t` function override
- `defaultLanguage`
- `translationScope`

2022-02-01 11:36 UTC, rishabhpoddar commented on examples/for-tests/src/App.js
> +        translations: {
If this name is changing, we should also change the name of the functions in the index.ts files

2022-02-01 11:36 UTC, rishabhpoddar commented on lib/ts/index.ts
> +    static changeLanguage(language: string): void {
Also export useTranslations cause the user might want to use it during override

2022-02-01 11:36 UTC, rishabhpoddar commented on lib/ts/components/translationContext.tsx
> +                console.warn(`Missing translation ${key} from ${currentLanguage}`);
Do these only if in dev mode?

2022-02-01 11:36 UTC, rishabhpoddar commented on lib/ts/translationHelpers.tsx
> +// type TranslationContext = Record<string, Record<Record<string, string>>>;
Not sure why this comment is here..

2022-02-01 11:36 UTC, rishabhpoddar commented on lib/ts/translationHelpers.tsx
> +    return getCookieValue(CURRENT_LANGUAGE_COOKIE_NAME);
Add a try  catch and if that fails, ignore it and return `null`

2022-02-01 11:36 UTC, rishabhpoddar commented on lib/ts/translationHelpers.tsx
> +    setFrontendCookie(CURRENT_LANGUAGE_COOKIE_NAME, language, cookieDomain);
Add a try  catch and if that fails, ignore it and return `null`

2022-02-01 11:36 UTC, rishabhpoddar commented on lib/ts/utils.ts
> +export function normaliseCookieScopeOrThrowError(cookieScope: string): string {
Maybe import from supertokens-website instead.

2022-02-01 11:54 UTC, rishabhpoddar requested changes

2022-02-01 11:54 UTC, rishabhpoddar commented on lib/ts/recipe/thirdparty/translations.ts
> +        THIRD_PARTY_SIGN_IN_UP_FOOTER_END: "",
Missing "continue with <provider>" text?

2022-02-01 11:54 UTC, rishabhpoddar commented on lib/ts/recipe/thirdparty/translations.ts
> +        THIRD_PARTY_SIGN_IN_UP_FOOTER_AND: "and",
Need to add sapces around the and

2022-03-04 10:20 UTC, porcellus commented
This was manually merged into the thirdpartypasswordless PR

2022-03-04 10:20 UTC, closed without merging