chore: Merge 0.21 into web-js-integration
supertokens/supertokens-auth-react pull request #455
Opened 2022-05-19 10:44 UTC by nkshah2

## Summary of change

- Merges the latest code base for auth-react into web-js-integration

## Related issues

-   https://github.com/supertokens/for-zenhub/issues/28

## Test Plan

All existing test cases should pass

## Documentation changes

WIP

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
    -   Along with the associated array in `lib/ts/version.ts`
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If added a new recipe interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If I added a new recipe, I also added the recipe entry point into the `size-limit` section of `package.json` with the size limit set to the current size rounded up.

## Remaining TODOs for this PR

-   [ ] ...

2022-05-19 22:33 UTC, porcellus requested changes

2022-05-19 22:33 UTC, porcellus commented on lib/ts/recipe/passwordless/components/features/linkClickedScreen/index.tsx
> +import STGeneralError from "supertokens-web-js/lib/build/error";
import from `/build`

2022-05-20 05:36 UTC, nkshah2 commented on lib/ts/recipe/thirdparty/components/features/signInAndUpCallback/index.tsx
> +                return props.recipe.redirectToAuthWithRedirectToPath(undefined, props.history, {
Youre right, it should be `redirectToAuthWithoutRedirectToPath`. Changed this in `passwordless/components/features/linkClickedScreen/index` as well

2022-05-20 07:44 UTC, porcellus approved these changes

2022-05-24 08:37 UTC, merged