feat: move override config to stwrapper
supertokens/supertokens-auth-react pull request #636
Opened 2022-12-25 07:01 UTC by alisher-aituarov

## Summary of change

Moves components override to separate component unique for each recipe

## Related issues

-   https://github.com/supertokens/supertokens-auth-react/issues/616

## Test Plan

## Documentation changes

- https://github.com/supertokens/docs/pull/562

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If added a new recipe interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If I added a new recipe, I also added the recipe entry point into the `size-limit` section of `package.json` with the size limit set to the current size rounded up.

## Remaining TODOs for this PR

-   [ ] change docs
-   [ ] finish writing test

2022-12-26 07:27 UTC, alisher-aituarov commented
Some test fail on this branch and on 0.28 as well

2022-12-28 17:27 UTC, porcellus requested changes
- Please manually test the updated examples (or confirm you already did)
- I'd prefer if we threw an error if the user adds overrides for a recipe that hasn't been initialized. A meaningful error message and an early failure could help devs who try to add emailpassword overrides for thirdpartyemailpassword using the wrong context provider. (Please also add a test for this)

2022-12-28 17:27 UTC, porcellus commented on test/unit/componentOverrides.test.tsx
> +    it.skip("Should not affect other recipes components when the same component is overridden", async () => {
Why is this skipped?

2022-12-28 17:27 UTC, porcellus commented on test/unit/componentOverrides.test.tsx
> +    it.skip("Should not affect other recipes components when the same component is overridden", async () => {
Please add another version of this test without `ThirdpartyEmailPasswordComponentsOverrideProvider` and check that the default is displayed.

2022-12-28 17:27 UTC, porcellus commented on test/unit/componentOverrides.test.tsx
> +    it.skip("Should not affect other recipes components when the same component is overridden", async () => {
Actually, the other test-case already includes checking with two different recipe specific contexts, so you can just update this test case

2022-12-29 05:07 UTC, alisher-aituarov commented on lib/ts/recipe/emailpassword/componentOverrideContext.tsx
> +    Consumer as RecipeComponentsOverrideContextConsumer,
issue is created

2022-12-29 05:44 UTC, alisher-aituarov commented
> * Please manually test the updated examples (or confirm you already did)
> * I'd prefer if we threw an error if the user adds overrides for a recipe that hasn't been initialized. A meaningful error message and an early failure could help devs who try to add emailpassword overrides for thirdpartyemailpassword using the wrong context provider. (Please also add a test for this)

Manually tested examples that i had to update

2022-12-29 09:59 UTC, alisher-aituarov commented
application is rendered before supertokens gets initialized, hence we are not able to access list of recipes while creating the context for recipe

2022-12-29 09:59 UTC, alisher-aituarov commented
> @porcellus  application is rendered before supertokens gets initialized, hence we are not able to access list of recipes while creating the context for recipe. 
For now leaving as is

2022-12-29 13:51 UTC, porcellus approved these changes

2022-12-30 08:49 UTC, porcellus approved these changes

2023-01-04 06:59 UTC, rishabhpoddar requested changes

2023-01-04 06:59 UTC, rishabhpoddar commented on CHANGELOG.md
> +-   Moved component override config into a recipe specific provider component
add migration guide

2023-01-04 06:59 UTC, rishabhpoddar commented on CHANGELOG.md
> +### Changed
```suggestion
### Breaking changes
```

2023-01-05 08:34 UTC, rishabhpoddar requested changes

2023-01-05 08:34 UTC, rishabhpoddar commented on CHANGELOG.md
> +#### EmailVerification recipe init
```suggestion
```

2023-01-05 08:38 UTC, rishabhpoddar requested changes

2023-01-05 11:37 UTC, rishabhpoddar approved these changes

2023-01-06 05:32 UTC, rishabhpoddar approved these changes

2023-01-06 05:44 UTC, merged