Feat/sort imports
supertokens/supertokens-auth-react pull request #648
Opened 2023-01-26 08:09 UTC by alisher-aituarov

## Summary of change

Enforce import ordering
Add consistent type imports 

## Related issues

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If added a new recipe interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If I added a new recipe, I also added the recipe entry point into the `size-limit` section of `package.json` with the size limit set to the current size rounded up.
-   [ ] If I added a new recipe, I also added the recipe entry point into the `rollup.config.mjs`

## Remaining TODOs for this PR

2023-01-27 09:50 UTC, porcellus requested changes
This looks good, just a few checks:
- [ ] The commit hook fails if you add an import in the wrong place/without type
- [ ] These changes come from an auto-fixer of these rules
- [ ] Please check that one exists/add an npm script to automatically fix these lint errors

2023-02-04 03:00 UTC, alisher-aituarov commented
> This looks good, just a few checks:
> 
> * [ ]  The commit hook fails if you add an import in the wrong place/without type
> * [ ]  These changes come from an auto-fixer of these rules
> * [ ]  Please check that one exists/add an npm script to automatically fix these lint errors

Added command that fixes all eslint issues it can fix so that hook passes

2023-02-05 09:38 UTC, porcellus approved these changes

2023-02-07 06:48 UTC, rishabhpoddar approved these changes

2023-02-07 06:49 UTC, merged