fix: keep query redirectToPath's query params when redirecting from auth
supertokens/supertokens-auth-react pull request #653
Opened 2023-02-06 12:11 UTC by alisher-aituarov

## Summary of change

Makes redirectToPath's query params stay when redirecting to it from auth route

## Related issues

- https://github.com/supertokens/supertokens-web-js/issues/82

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If added a new recipe interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If I added a new recipe, I also added the recipe entry point into the `size-limit` section of `package.json` with the size limit set to the current size rounded up.
-   [ ] If I added a new recipe, I also added the recipe entry point into the `rollup.config.mjs`

## Remaining TODOs for this PR

2023-02-06 23:13 UTC, porcellus requested changes
The changes look good, but please add tests. There are a few `redirectToPath` tests already there that you can use as a base.

2023-02-22 20:15 UTC, porcellus requested changes

2023-02-22 20:15 UTC, porcellus commented on test/end-to-end/signin.test.js
> +                page.goto(
Please add a similar ones that test the redirection:
- emailpassword sign-in 
- emailpassword sign-up.
- passwordless sign-in
- thirdparty sign-in

This test only cheks that the auth pages redirect to the appropriate path if we navigate to it while already logged in.

2023-02-22 20:15 UTC, porcellus commented on lib/ts/utils.ts
> +            const pathQueryParams = param.split("?")[1] ? `?${param.split("?")[1]}` : "";
please add a strict undefined check, so we can preserve paths ending in a `?`

2023-03-02 09:52 UTC, porcellus requested changes

2023-03-02 09:52 UTC, porcellus commented on lib/ts/utils.ts
> +            const pathQueryParams = param.split("?")[1] ? `?${param.split("?")[1]}` : "";
This didn't happen.

2023-03-02 09:52 UTC, porcellus commented on lib/ts/utils.ts
> +export function getRedirectToPathFromURL({ includeQueryParams } = { includeQueryParams: false }): string | undefined {
Is this used anywhere without this param set to true?

2023-03-03 15:04 UTC, porcellus requested changes
Please remove the parameter of `getRedirectToPathFromURL` if it's always used with the same parameter.

2023-03-07 11:53 UTC, rishabhpoddar approved these changes

2023-03-07 11:53 UTC, merged