update iframe example app
supertokens/supertokens-auth-react pull request #657
Opened 2023-02-17 05:14 UTC by alisher-aituarov

## Summary of change

Update example apps according to latest release 

## Related issues

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If added a new recipe interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If I added a new recipe, I also added the recipe entry point into the `size-limit` section of `package.json` with the size limit set to the current size rounded up.
-   [ ] If I added a new recipe, I also added the recipe entry point into the `rollup.config.mjs`

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2023-02-22 20:18 UTC, porcellus commented
Please add a comment about which examples you checked/ran locally.

2023-02-26 17:09 UTC, rishabhpoddar commented
@alisher-aituarov whats the status on this issue? It's been pending since a while now.

2023-03-01 16:17 UTC, rishabhpoddar commented
@alisher-aituarov @porcellus is this ready to merge?

2023-03-03 15:01 UTC, porcellus approved these changes

2023-03-07 11:49 UTC, rishabhpoddar requested changes

2023-03-07 11:49 UTC, rishabhpoddar commented on examples/with-next-iframe/config/frontendConfig.js
> +                tokenTransferMethod: "header",
does this make the examlpe work on safari and incognito chrome? If yes, please update the readme in this example app cause it has a "### IMPORTANT:" section which needs to be removed.

2023-03-07 13:14 UTC, rishabhpoddar approved these changes

2023-03-07 13:14 UTC, merged