feat: duplicate init split prebuilt UI
supertokens/supertokens-auth-react pull request #665
Opened 2023-03-15 08:15 UTC by alisher-aituarov

## Summary of change

Combination of https://github.com/supertokens/supertokens-auth-react/pull/640 & https://github.com/supertokens/supertokens-auth-react/pull/655

## Related issues

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If added a new recipe interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If I added a new recipe, I also added the recipe entry point into the `size-limit` section of `package.json` with the size limit set to the current size rounded up.
-   [ ] If I added a new recipe, I also added the recipe entry point into the `rollup.config.mjs`

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2023-03-31 12:44 UTC, porcellus requested changes
Please add a check to examples you manual tested (and test the missing ones) using the latest version:
- [x] with-next-iframe
- [x] with-multiple-email-sign-in
- [x] with-phone-password
- [ ] with-sign-in-up-split-emailpassword
- [ ] with-svelte-react-thirdpartyemailpassword
- [ ] with-thirdpartyemailpassword-2fa-passwordless
- [ ] with-thirdpartyemailpassword-passwordless
- [ ] with-thirdpartypasswordless-electron

Plus test that the new branch of create-supertokens-app creates a working example for different configs:
- [ ] angular & node w/ thirdpartyemailpassword
- [ ] react & node w/ thirdpartyemailpassword
- [ ] vue & node w/ thirdpartyemailpassword
- [ ] nextjs
- [ ] capacitor

2023-03-31 12:44 UTC, porcellus commented on examples/for-tests/src/AppWithoutRouter.js
> +            return ThirdPartyPreBuiltUI.canHandleRoute() && EmailPasswordPreBuiltUI.canHandleRoute();
```suggestion
            return ThirdPartyPreBuiltUI.canHandleRoute() || EmailPasswordPreBuiltUI.canHandleRoute();
```

2023-04-16 21:54 UTC, porcellus requested changes
Please complete the above checklist after the latest changes (I've unchecked everything)

2023-05-02 16:40 UTC, rishabhpoddar requested changes

2023-05-02 16:40 UTC, rishabhpoddar commented on CHANGELOG.md
>  ## [unreleased]
change in this

2023-05-02 16:40 UTC, rishabhpoddar commented on CHANGELOG.md
> +
add that we should not init both web-js and auth-react -> just one of them

2023-05-02 16:40 UTC, rishabhpoddar commented on examples/for-tests-react-16/src/AppWithReactDomRouter.js
>  import React, { useState } from "react";
need to update google one tap example app (if this does not work on chrome, try firefox)

2023-05-02 17:14 UTC, rishabhpoddar approved these changes

2023-05-02 17:14 UTC, merged