fix: import UI
supertokens/supertokens-auth-react pull request #687
Opened 2023-05-05 08:14 UTC by alisher-aituarov

## Summary of change

Fixes import issue when using vite 

## Related issues

-  [Issue](https://github.com/supertokens/supertokens-core/issues/664)
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If added a new recipe interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If I added a new recipe, I also added the recipe entry point into the `size-limit` section of `package.json` with the size limit set to the current size rounded up.
-   [ ] If I added a new recipe, I also added the recipe entry point into the `rollup.config.mjs`

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2023-05-05 08:44 UTC, porcellus approved these changes

2023-05-06 18:40 UTC, rishabhpoddar approved these changes

2023-05-06 18:43 UTC, rishabhpoddar requested changes

2023-05-06 18:43 UTC, rishabhpoddar commented on CHANGELOG.md
>  ## [unreleased]
- Update the patch version please.
- Is there anything we can add to the tests / CICD / pre commit hooks that can ensure this type of error doesn’t happen again?
- One of the PR checks for the example app is failing. Please see why.
- You can remove the example pr checks for emailpassword, passwordless, thirdparty, thirdpartyemailpassword, thirdpartypasswordless and supabase.

2023-05-11 07:30 UTC, merged