chore: jwt rework
supertokens/supertokens-auth-react pull request #692
Opened 2023-05-12 04:04 UTC by alisher-aituarov

## Summary of change

Updates example apps 

## Related issues

-   Link to issue1 here
-   Link to issue1 here

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Documentation changes

(If relevant, please create a PR in our [docs repo](https://github.com/supertokens/docs), or create a checklist here highlighting the necessary changes)

## Checklist for important updates

-   [ ] Changelog has been updated
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)
-   [ ] Changes to the version if needed
    -   In `package.json`
    -   In `package-lock.json`
    -   In `lib/ts/version.ts`
-   [ ] Had run `npm run build-pretty`
-   [ ] Had installed and ran the pre-commit hook
-   [ ] Issue this PR against the latest non released version branch.
    -   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
    -   If no such branch exists, then create one from the latest released branch.
-   [ ] If added a new recipe interface, then make sure that the implementation of it uses NON arrow functions only (like `someFunc: function () {..}`).
-   [ ] If I added a new recipe, I also added the recipe entry point into the `size-limit` section of `package.json` with the size limit set to the current size rounded up.
-   [ ] If I added a new recipe, I also added the recipe entry point into the `rollup.config.mjs`

## Remaining TODOs for this PR

-   [ ] Item1
-   [ ] Item2

2023-05-15 12:50 UTC, porcellus requested changes

2023-05-15 12:50 UTC, porcellus commented on examples/with-thirdpartyemailpassword-2fa-passwordless/api-server/index.ts
> +                        },
why is this required?

2023-05-15 12:50 UTC, porcellus commented on examples/with-hasura-thirdpartyemailpassword/src/Home/CallAPIView.js
> +        }
We don't really need to migration code in our examples.

```suggestion
        const jwt = Session.getAccessToken();
```

2023-05-15 12:50 UTC, porcellus commented on examples/with-hasura-thirdpartyemailpassword/api-server.js
> +            getTokenTransferMethod: () => "header",
Why did this change?

```suggestion
            exposeAccessTokenToFrontendInCookieBasedAuth: true,
```

2023-05-15 12:50 UTC, porcellus commented on examples/with-hasura-thirdpartyemailpassword/api-server.js
> +                            jwks_uri: `${apiDomain}/auth/jwt/jwks.json`,
```suggestion
                            jwks_uri: `${process.env.JWT_ISSUER_URL}/auth/jwt/jwks.json`,
```

2023-05-15 12:50 UTC, porcellus commented on examples/with-emailverification-then-password-thirdpartyemailpassword/api-server.js
> +            exposeAccessTokenToFrontendInCookieBasedAuth: true,
why is this required?

2023-05-16 09:17 UTC, porcellus requested changes

2023-05-16 09:17 UTC, porcellus commented on examples/with-hasura-thirdpartyemailpassword/api-server.js
> +                            jwks_uri: `${process.env.JWT_ISSUER_URL}/auth/jwt/jwks.json`,
```suggestion
                            jwks_uri: `${process.env.JWT_ISSUER_URL}/jwt/jwks.json`,
```

2023-05-16 09:17 UTC, porcellus approved these changes

2023-05-16 09:18 UTC, porcellus requested changes

2023-05-16 09:18 UTC, porcellus commented on examples/with-hasura-thirdpartyemailpassword/src/Home/CallAPIView.js
> +        const jwt = Session.getAccessToken();
```suggestion
        const jwt = await Session.getAccessToken();
```

2023-05-16 09:19 UTC, porcellus approved these changes

2023-05-16 09:27 UTC, rishabhpoddar approved these changes

2023-05-16 09:28 UTC, merged